# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Esolang < Formula
  desc "Esolang - A novice oriented programming language."
  homepage "https://github.com/ahmedsaheed/esolang"
  version "0.1.2"

  on_macos do
    on_intel do
      url "http://github.com/ahmedsaheed/esolang/releases/download/v0.1.2/esolang_Darwin_x86_64.tar.gz"
      sha256 "2808bfd136acd0a4346f7beba014d87a88fe6286ebf8b3846735d505bfbbd12c"

      def install
        bin.install "esolang"
      end
    end
    on_arm do
      url "http://github.com/ahmedsaheed/esolang/releases/download/v0.1.2/esolang_Darwin_arm64.tar.gz"
      sha256 "3eebcb58a7447efdf60bad3e32ed3d947f30fa700f45324a2d5cad2420a951d1"

      def install
        bin.install "esolang"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "http://github.com/ahmedsaheed/esolang/releases/download/v0.1.2/esolang_Linux_x86_64.tar.gz"
        sha256 "558dafff98ddb5f84106022c44bd7f3f078c4bb345a6743949e97541da4fdf46"

        def install
          bin.install "esolang"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "http://github.com/ahmedsaheed/esolang/releases/download/v0.1.2/esolang_Linux_arm64.tar.gz"
        sha256 "3792f80bcb52effd8ab8dc52d9f81759250b52d4797f8a011124e9674b2b356b"

        def install
          bin.install "esolang"
        end
      end
    end
  end
end
